# Generated by Django 5.0.2 on 2024-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_account_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='-', max_length=8),
            preserve_default=False,
        ),
    ]
