# Generated by Django 4.2.6 on 2023-10-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_deleted_at_alter_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('transactions.transaction',),
        ),
    ]
