# Generated by Django 4.2.6 on 2023-10-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactiontemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionTemplate',
        ),
    ]
